version: '3.9'

networks:
  internal_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-shortener}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      internal_net:
        aliases:
          - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-shortener}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"

  # Сервис для тестирования соединения с базой данных
  db-test:
    image: postgres:17-alpine
    container_name: db-test
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-shortener}
    volumes:
      - ./docker/test-db-connection.sh:/test-db-connection.sh
    networks:
      - internal_net
    command: /test-db-connection.sh
    profiles:
      - debug

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minifylink
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/app/config/prod.yaml
      - VIRTUAL_HOST=шайтанкод.рф
      - LETSENCRYPT_HOST=шайтанкод.рф
      - LETSENCRYPT_EMAIL=поддержка@шайтанкод.рф
    volumes:
      - ./config:/app/config
    networks:
      - internal_net
      - nginx_proxy
    expose:
      - "8082"

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./nginx-data:/etc/nginx/conf.d
    networks:
      - nginx_proxy

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    restart: always
    environment:
      - DEFAULT_EMAIL=поддержка@шайтанкод.рф
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    networks:
      - nginx_proxy
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
    driver: local
  certs:
  vhost:
  html:
  acme:
