FROM nginx:latest

COPY nginx-external.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/certs
COPY /etc/nginx/cert/шайтанкод.рф.crt /etc/nginx/certs/
COPY /etc/nginx/cert/шайтанкод.рф.key /etc/nginx/certs/

RUN chmod 644 /etc/nginx/certs/шайтанкод.рф.crt \
    && chmod 600 /etc/nginx/certs/шайтанкод.рф.key
