// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LinkSaver is an autogenerated mock type for the LinkSaver type
type LinkSaver struct {
	mock.Mock
}

// SaveLink provides a mock function with given fields: linkToSave, shortID
func (_m *LinkSaver) SaveLink(linkToSave string, shortID string) error {
	ret := _m.Called(linkToSave, shortID)

	if len(ret) == 0 {
		panic("no return value specified for SaveLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(linkToSave, shortID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLinkSaver creates a new instance of LinkSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkSaver {
	mock := &LinkSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
