// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LinkGetter is an autogenerated mock type for the LinkGetter type
type LinkGetter struct {
	mock.Mock
}

// GetLink provides a mock function with given fields: alias, country, device, browser
func (_m *LinkGetter) GetLink(alias string, country string, device string, browser string) (string, error) {
	ret := _m.Called(alias, country, device, browser)

	if len(ret) == 0 {
		panic("no return value specified for GetLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (string, error)); ok {
		return rf(alias, country, device, browser)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(alias, country, device, browser)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(alias, country, device, browser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLinkGetter creates a new instance of LinkGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkGetter {
	mock := &LinkGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
