name: Run Go Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build minifylink container
        run: docker-compose build minifylink

      - name: Start container
        run: docker-compose up -d minifylink

      - name: Wait for container to start
        run: |
          TIMEOUT=30
          INTERVAL=5
          START_TIME=$(date +%s)
          
          while ! docker ps | grep -q minifylink; do
            if (( $(date +%s) - START_TIME >= TIMEOUT )); then
              echo "Контейнер не запустился за отведенное время"
              docker ps
              exit 1
            fi
            echo "Ожидание запуска контейнера..."
            sleep $INTERVAL
          done
          echo "Контейнер запущен"

      - name: Run tests
        run: docker exec -t minifylink sh -c "go test -v ./... -cover"

      - name: Generate coverage report
        if: success()
        run: |
          mkdir -p coverage
          docker exec -t minifylink sh -c "go test -coverprofile=/app/coverage.out ./..."
          docker cp minifylink:/app/coverage.out ./coverage/

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Print container logs on failure
        if: failure()
        run: docker logs minifylink
