name: Run Tests on Server

on:
  workflow_run:
    workflows: ["update-repo"]
    types:
      - completed
    branches: [ main, deploy ]
  push:
    branches: [ main, deploy ]

jobs:
  test:
    name: Run Remote Tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Run tests on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            echo "Запуск тестов на сервере..."
            cd backend

            if [ "$(docker inspect --format='{{.State.Health.Status}}' minifylink 2>/dev/null)" == "healthy" ]; then
              echo "Контейнер minifylink в состоянии healthy, запускаем тесты"
              
              echo "Проверка структуры проекта..."
              docker exec -t minifylink sh -c "ls -la /app"
              docker exec -t minifylink sh -c "ls -la /app/internal"
              
              echo "Запуск тестов..."
              docker exec -t minifylink sh -c "cd /app && go test -v ./internal/... ./cmd/... -cover"
              
              echo "Генерация отчета о покрытии..."
              docker exec -t minifylink sh -c "cd /app && go test -coverprofile=/app/coverage.out ./internal/... ./cmd/..."
              
              echo "Анализ покрытия кода..."
              docker exec -t minifylink sh -c "cd /app && go tool cover -func=/app/coverage.out"
            else
              echo "Контейнер minifylink не запущен или не в состоянии healthy"
              docker ps | grep minifylink || echo "Контейнер не найден"
              exit 1
            fi