name: Update Repo

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}
      - name: Update repo
        run: |
          cd backend && git pull origin main
      - name: Update docker
        run: |
          docker-compose up -d --build 
